version: '3.8'
services:
    a-soft-api:
        container_name: a-soft-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - postgres
        env_file:
            - .env

    postgres:
        image: postgres:15.2
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        env_file:
            - .env
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - '5432:5432'

volumes:
    postgres:
        name: nest-db