version: '3.8'
services:
    a-soft-api:
        container_name: a-soft-api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        env_file:
            - .env